# Generated by Django 4.0.4 on 2022-05-15 15:46
# pylint: disable=invalid-name

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefreshTokenRotationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        editable=False,
                        help_text="Date and time when the token expires.",
                    ),
                ),
                (
                    "group",
                    models.UUIDField(
                        editable=False,
                        help_text="Group this refresh token belongs to.",
                    ),
                ),
            ],
        ),
    ]
